#Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: buggy-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: buggy-app
  template:
    metadata:
      labels:
        app: buggy-app
    spec:
      containers:
      - name: buggy-container
        image: 851725252845.dkr.ecr.us-east-1.amazonaws.com/buggy-app:v1
        imagePullPolicy: Always
        ports:
          - containerPort: 8080

---
#Service

apiVersion: v1
kind: Service
metadata: 
  name: buggy-svc
spec:
  type: LoadBalancer
  selector:
    app: buggy-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
